apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: dst-airlines
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: dst-airlines-api:ci
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: dst-airlines-secret
                  key: DATABASE_URL
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: dst-airlines-config
                  key: MONGO_URL
            - name: NEO4J_URL
              valueFrom:
                configMapKeyRef:
                  name: dst-airlines-config
                  key: NEO4J_URL
            - name: NEO4J_USER
              valueFrom:
                configMapKeyRef:
                  name: dst-airlines-config
                  key: NEO4J_USER
            - name: NEO4J_PASS
              valueFrom:
                secretKeyRef:
                  name: dst-airlines-secret
                  key: NEO4J_PASSWORD
            - name: GULF_MODEL_PATH
              valueFrom:
                configMapKeyRef:
                  name: dst-airlines-config
                  key: GULF_MODEL_PATH
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
