apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: dst-airlines
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "airlines"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dst-airlines-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: "airlines_db"
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - airlines
                - -d
                - airlines_db
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: pg-pvc
        - name: postgres-init
          configMap:
            name: postgres-init
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: dst-airlines
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pvc
  namespace: dst-airlines
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
