apiVersion: v1
kind: Secret
metadata:
  name: dst-airlines-secret
  namespace: dst-airlines
type: Opaque
stringData:
  POSTGRES_PASSWORD: "replace-me"
  NEO4J_PASSWORD: "replace-me"
  NEO4J_AUTH: "neo4j/replace-me"
  PGADMIN_PASSWORD: "replace-me"
  DATABASE_URL: "postgresql+psycopg2://airlines:replace-me@db:5432/airlines_db"
